<a href="<?php echo $this->url('myeconomic'); ?>" class="btn btn-default">Back to Dashboard</a><br>
<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <?php 
            echo $this->form()->openTag($form);
            foreach ($form as $element): ?>
                <div class="row form-group">
                    <label for="<?php echo $element->getName(); ?>" class="col-sm-4 control-label"><?php echo $element->getLabel(); ?></label>
                    <div class="col-sm-8">
                        <?php echo $this->formElement($element); ?>
                        <?php if ($this->formElementErrors($element)): ?>
                            <div class="alert alert-danger alert-dismissable">
                                <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
                                <?php echo $this->formElementErrors($element); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endforeach; ?>
            <div class="row">
                <div class="col-sm-4">
                     <button class="btn btn-success" type="submit">Update User Credentials</button>
                </div>
                <div class="col-sm-4">
                     <a href="<?php echo $this->url('myeconomic', array('action' => 'loaddata')); ?>" class="btn btn-info">Sync Your E-conomic Data</a>
                </div>
            </div>
            <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>
