<style>
    .img-circle img {
        border-radius: 50%;
    }
</style>

<div style="float:left; padding-right:16px;">
    <div class ='img-circle'>
        <?php echo $this->htProfileImage($this->zfcUserIdentity(), array('class'=>'img-circle'))?>
    </div>
</div>
<h3>
    <?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?>!
</h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">
    [<?php echo $this->translate('Sign Out'); ?>]
</a>
<div style="clear:both;"></div>
<a href="<?php echo $this->url('zfcuser/htimageupload') ?>">
    <?php echo $this->translate('Upload image'); ?>
</a>